services:
  my-app:
    build:
      context: .
      args:
        STUDENT_NAME: "Mario Richie Lim"
        STUDENT_NIM: "0000067355"
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
